[mcp_servers.chrome-devtools-mcp]
command = "npx"
args = ["-y", "@upstash/chrome-devtools-mcp@latest"，"--browser-url=http://127.0.0.1:9222"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "."]
